force-app/main/default/objects/Medical_Note__c/Medical_Note__c.object-meta.xml
<CustomObject>
    <label>Medical Note</label>
    <nameField>
        <displayFormat>MN-{0000}</displayFormat>
        <label>Medical Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Note__c/fields/Medicine__c.field-meta.xml
<CustomField>
    <fullName>Medicine__c</fullName>
    <label>Medicine</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MedicalsController.cls
public with sharing class MedicalsController {
    

    @AuraEnabled
    public static void updateMedicals(String recordId, String dataJSON){

        update new Medical_Note__c(Id = recordId, Medicine__c = dataJSON);

    }

    @AuraEnabled
    public static String getMedicals(String recordId){

        Medical_Note__c medicalNote = [SELECT Id, Medicine__c FROM Medical_Note__c WHERE Id =: recordId LIMIT 1];

        return medicalNote.Medicine__c;

    }

}