force-app/main/default/objects/Medical_History__c/Medical_History__c.object-meta.xml
<CustomObject>
    <label>Medical History</label>
    <nameField>
        <displayFormat>MH{00000}</displayFormat>
        <label>Medical history Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_History__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Medical_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_History__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Medical Histories</relationshipLabel>
    <relationshipName>Medical_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Note__c/Medical_Note__c.object-meta.xml
<CustomObject>
    <label>Medical Note</label>
    <nameField>
        <displayFormat>MN-{0000}</displayFormat>
        <label>Medical Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Note__c/fields/Medical_History__c.field-meta.xml
<CustomField>
    <fullName>Medical_History__c</fullName>
    <label>Medical History</label>
    <referenceTo>Medical_History__c</referenceTo>
    <relationshipLabel>Medical Notes</relationshipLabel>
    <relationshipName>Medical_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Note__c/fields/Medicine__c.field-meta.xml
<CustomField>
    <fullName>Medicine__c</fullName>
    <label>Medicine</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MedicinePDFController.cls
public with sharing class MedicinePDFController {
    public String medicalNoteId { get{
        return ApexPages.currentPage().getParameters().get('medicalNoteId');
    } set; }

    public Medical_Note__c medicalNoteItem;

    public List<MedicineWrapper> medicineWrapperList{get{

        if(medicalNoteItem==null)
            medicalNoteItem = [SELECT Id, Medicine__c, Medical_History__r.Patient__r.Name, Medical_History__r.Doctor__r.Name FROM Medical_Note__c WHERE Id =: medicalNoteId LIMIT 1];

        return medicalNoteItem.Medicine__c!=null?(List<MedicineWrapper>) JSON.deserialize(medicalNoteItem.Medicine__c, List<MedicineWrapper>.class):new List<MedicineWrapper>();
    } set;}


    public String logoImage{get{
        return 'VF_Logo';
    }set;}


    public String footerImage{get{
        return 'VF_Footer';
    }set;}

    public String watermarkImage{get{
        return 'VF_watermark';
    }set;}


    public String patientName{get{
        
        if(medicalNoteItem==null)
            medicalNoteItem = [SELECT Id, Medicine__c, Medical_History__r.Patient__r.Name, Medical_History__r.Doctor__r.Name FROM Medical_Note__c WHERE Id =: medicalNoteId LIMIT 1];

        return medicalNoteItem.Medical_History__r.Patient__r.Name;

    }set;}

    public String doctorName{get{
        
        if(medicalNoteItem==null)
            medicalNoteItem = [SELECT Id, Medicine__c, Medical_History__r.Patient__r.Name, Medical_History__r.Doctor__r.Name FROM Medical_Note__c WHERE Id =: medicalNoteId LIMIT 1];

        return medicalNoteItem.Medical_History__r.Doctor__r.Name;

    }set;}

    

    


    public class MedicineWrapper{
        public String id {get;set;}
        public String name {get;set;}
        public String dosage {get;set;}
        public String dosageForm {get;set;}
        public String frequency {get;set;}

    }

}